filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/caddy/access.log
    json.keys_under_root: true
    json.add_error_key: true
    tags: ["caddy"]
    fields:
      app: microcrm-front
      env: docker
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: warning
